### ISSUE TITLE
HeaderBar 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by Hwa-J** [onulstore/Onulstore-FE#11]
## Description

HeaderBar 컴포넌트 관련 리팩토링

## Todo List

- [x] 로고 및 뒤로가기 화살표 스타일 수정
- [x] 현재 위치 (HeaderCenter) 리팩토링
- [x] 아이콘 `cursor: pointer;` 안되는 버그 수정
