### ISSUE TITLE
Home 페이지 제작

### ISSUE THREAD

**Issue by Hwa-J** [onulstore/Onulstore-FE#113]
## Description
Home 페이지 제작 및 관련 컴포넌트 병합합니다.

## Todo List

- [x] 오늘 날짜시간 컴포넌트 제작
- [x] 홈배너 병합
- [x] 오늘할인 병합
- [x] Magazine 병합
- [x] Our Picks 병합
- [x] TODAY’s TREND 컴포넌트 제작
- [x] INSTAGRAM 컴포넌트 제작
