### ISSUE TITLE
Home page의 NavBar 슬라이드 기능 구현

### ISSUE THREAD

**Issue by Hwa-J** [onulstore/Onulstore-FE#13]
## Description

홈 페이지의 NavBar 슬라이드 기능 구현
![스크린샷 2022-09-26 오전 3 24 13](https://user-images.githubusercontent.com/99096272/192159183-435b6f2c-9f67-4665-bf20-99be9b9a9225.png)

## Todo List

- [x] 메뉴 스크롤(스왑)
- [x] 포커스된 메뉴와 아닌 메뉴 구분
- [ ] JUST FOR TODAY 기본 포커스
