### ISSUE TITLE
Total Result Value Bar 및 Select Box 컴포넌트 제작

### ISSUE THREAD

**Issue by Hwa-J** [onulstore/Onulstore-FE#131]
## Description
- Total Result Value Bar 
![스크린샷 2022-10-21 오후 11 00 59](https://user-images.githubusercontent.com/99096272/197214088-e8ae707b-dde0-49d9-90f6-0f5a1e8eca35.png)
- Select Box
![스크린샷 2022-10-21 오후 11 13 45](https://user-images.githubusercontent.com/99096272/197216840-a225fb92-0bef-4955-bbfb-d448bccf1cbc.png)

## Todo List

- [x] Total Result Value Bar 컴포넌트 제작
- [x] Select Box 컴포넌트 제작
- [x] Sorter 컴포넌트에 연결할 Slice action 구현
