### ISSUE TITLE
auth api 연결

### ISSUE THREAD

**Issue by k-m-jin** [onulstore/Onulstore-FE#68]
## Description

인증 관련된 api 로직 개발
## Todo List

- [x] axios interceptor res
- [ ] axios interceptor req
- [x] 유저 정보 전역으로 관리
