### ISSUE TITLE
Today 페이지 컴포넌트 제작

### ISSUE THREAD

**Issue by Hwa-J** [onulstore/Onulstore-FE#91]
## Description
- 상단
![스크린샷 2022-10-12 오후 11 49 36](https://user-images.githubusercontent.com/99096272/195375454-9e60d4b9-4ccf-4285-9d05-e4d507f7b0be.png)
- 상품
![스크린샷 2022-10-12 오후 11 49 53](https://user-images.githubusercontent.com/99096272/195375514-a4636616-00b0-4949-92bf-baebd9ff3528.png)

## Todo List

- [x] Today 페이지 상단 배너 컴포넌트 구현
- [x] Today 상품 컴포넌트 구현
- [x] Today 페이지에 병합
