### ISSUE TITLE
We Like Magazine 페이지 컴포넌트 제작

### ISSUE THREAD

**Issue by Hwa-J** [onulstore/Onulstore-FE#98]
## Description
We Like Magazine 페이지 컴포넌트 제작입니다.

![스크린샷 2022-10-13 오전 5 28 23](https://user-images.githubusercontent.com/99096272/195441344-9e7f94b8-fbc6-4e57-ac21-ed6073cb2236.png)

## Todo List

- [x] We Like 페이지 하위 라우트로 Magazine 컴포넌트 생성
- [x] Magazine, Our Picks 네비게이션 바 제작
- [x] Magazine 리스트 컴포넌트 생성
